### PR TITLE
addPost() and getPost()

### PR DESCRIPTION
**Pull request by pleiadi666**

### CODE REVIEW

**Comment by pleiadi666** [comment]
Why?

**Comment by Blaxus** [comment]
Because I see you're rewriting the entire system and I don't like where this is going. No explanation what it does, no docs. You can just make a fork without modding the original if you want. But I see no need to refactor it the way you are doing it.

**Comment by pleiadi666** [comment]
@Blaxus I'm not leaving docs because my english is pretty bad. I'm rewriting the system in the right way: specs and S.O.L.I.D principles. Tests should explain what I'm doing.

What's the problem?

**Comment by Blaxus** [comment]
@pleiadi666 The problem is I'm not following S.O.L.I.D principles. I'm following KISS.
Here is my perspective. My Project, My Rules; Your project, Your rules.

You can make a S.O.L.I.D version if you want. So just make your own repository. I'm 100% sure there will be plenty of people interested in your version. But that doesn't mean I can't have my KISS version.

If your code does not follow the projects guidelines of my project. I will not merge your code.  I should have made that clear earlier.

**Comment by pleiadi666** [comment]
OMG! Are you serious? You are not follow KISS at all!

**Comment by Blaxus** [comment]
I don't care. My Project, My Rules. Make your own project.

**Pull request closed without merging**
